# Generated by Django 4.2.1 on 2023-06-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="asignatura",
        ),
    ]
