# Generated by Django 4.2.1 on 2023-06-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0004_file_asignatura"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="asignatura",
            new_name="asignatura_file",
        ),
    ]
