# Generated by Django 4.2.1 on 2023-06-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0005_rename_asignatura_file_asignatura_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="filemanager.folder",
            ),
        ),
    ]
