# Generated by Django 4.2.3 on 2023-07-23 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0006_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='usuario_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_file', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='usario_folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_folder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
