# Generated by Django 4.2.3 on 2023-07-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0007_file_usuario_file_folder_usario_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='usario_folder',
            new_name='usuario_folder',
        ),
    ]
