# Generated by Django 4.2.3 on 2023-07-28 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_dashboard_app', '0002_asignatura_usuario'),
        ('filemanager', '0009_alter_file_folder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('usuario_file', 'asignatura_file', 'folder', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('usuario_folder', 'asignatura', 'parent', 'name')},
        ),
    ]
