# Generated by Django 4.2.4 on 2023-08-15 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student_dashboard_app", "0002_asignatura_usuario"),
        ("filemanager", "0010_alter_file_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AskFolderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_consulta_folder", models.DateTimeField(auto_now_add=True)),
                (
                    "ask_asignatura_folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ask_asignatura_folder",
                        to="student_dashboard_app.asignatura",
                    ),
                ),
                (
                    "ask_folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ask_folder",
                        to="filemanager.folder",
                    ),
                ),
                (
                    "ask_usuario_folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ask_usuario_folder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AskAsignaturaLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_consulta_asignatura", models.DateTimeField(auto_now_add=True)),
                (
                    "ask_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ask_asignatura",
                        to="student_dashboard_app.asignatura",
                    ),
                ),
                (
                    "ask_usuario_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ask_usuario_asignatura",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
