# Generated by Django 4.2.4 on 2023-08-15 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_dashboard_app", "0002_asignatura_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("filemanager", "0010_alter_file_unique_together_and_more"),
        ("askapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_consulta", models.DateTimeField(auto_now_add=True)),
                (
                    "ask_asignatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ask_asignatura",
                        to="student_dashboard_app.asignatura",
                    ),
                ),
                (
                    "ask_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ask_folder",
                        to="filemanager.folder",
                    ),
                ),
                (
                    "ask_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ask_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="askfolderlog",
            name="ask_asignatura_folder",
        ),
        migrations.RemoveField(
            model_name="askfolderlog",
            name="ask_folder",
        ),
        migrations.RemoveField(
            model_name="askfolderlog",
            name="ask_usuario_folder",
        ),
        migrations.DeleteModel(
            name="AskAsignaturaLog",
        ),
        migrations.DeleteModel(
            name="AskFolderLog",
        ),
    ]
