# Generated by Django 4.2.3 on 2023-07-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
